### ISSUE TITLE
[Feature] Don't use the `KHR_texture_basisu` plugin

### ISSUE THREAD

**Issue by kanerogers** [leetvr/squisher#1]
## Background
![image](https://user-images.githubusercontent.com/2022375/178288531-8637c2c5-f36c-4510-baba-cb63fb1dd509.png)

**Comment by expenses** [comment]
Don't get me wrong, using the extension is the right idea if you want textures to look decent when the extension isn't implemented. But if you're targeting once specific application then skipping it might be easier.

**Comment by kanerogers** [comment]
> Don't get me wrong, using the extension is the right idea if you want textures to look decent when the extension isn't implemented. But if you're targeting once specific application then skipping it might be easier.

Well, the naughty thing we were doing was _not_ even providing a fallback image. So, it was a bit pointless in hindsight 😆
