### ISSUE TITLE
Handle already-squished models gracefully

### ISSUE THREAD

**Issue by LPGhatguy** [leetvr/squisher#17]
Currently, `squisher` bails when it encounters a model that it created previously. We should be able to skip over those textures and continue squishing anything we can.

**Comment by kanerogers** [comment]
Oooh this is a good point. But just to clarify is it bailing if the same model is present multiple times in the same file? Or if it has already previously processed that file?

**Comment by LPGhatguy** [comment]
Err, I guess we should probably just make it so that any `image/ktx2` textures get preserved as-is, and continue squishing the file.

**Comment by kanerogers** [comment]
> Err, I guess we should probably just make it so that any `image/ktx2` textures get preserved as-is, and continue squishing the file.

Oh! Forehead slap moment. Now I get you:

If squisher finds an image that's already in image/ktx2 format it should just ignore it.

That makes perfect sense!
