### ISSUE TITLE
After correcting the lines of code (hardcode the path) still an error :-(

### ISSUE THREAD

**Issue by cstfan** [leetvr/squisher#4]
After correcting lines 293 and 303 of code (hardcode the path) still an error :

![image](https://user-images.githubusercontent.com/33685211/180238063-590714f9-fea0-4e01-be9a-d014d1488264.png)

**Comment by kanerogers** [comment]
Oh dear! That's quite frustrating :-(

Are you able to check which file it's trying to read there (on line 288)?

**Comment by cstfan** [comment]
The BoxTexturedBinary.glb file does open in a gltf viewer, but on line 288 it may be another file that is extracted from the gltf that your program is trying to read ?

**Comment by kanerogers** [comment]
> The BoxTexturedBinary.glb file does open in a gltf viewer, but on line 288 it may be another file that is extracted from the gltf that your program is trying to read ?

Sorry I took so long to reply! 

I'm not sure that's the case - more likely that's the *temporary* file that can't be read. I'm guessing in this case ktx2ktx2 didn't run correctly. You could add a `println` to its output to see if it's telling you anything
