### ISSUE TITLE
Improvements to "productionize" Squisher

### ISSUE THREAD

**Issue by LPGhatguy** [leetvr/squisher#7]
Squisher is a great tool! I think there's some low-hanging fruit for things we can change to spruce it up.

- [x] Get rid of absolute paths. We should be able to rely on users having the dependent tools on their system PATH.
- [x] Adopt `clap` for command line arguments. We can replace the global consts with this, introduce compression configurability, and support named input/output files.
- [x] Use the `anyhow` crate for handling errors gracefully to avoid the Rust panic spew on error.
- [x] Use the `log` crate for supporting multiple log levels. This also helps us log to `stderr` instead of `stdout`, which is conventional.
- [x] Introduce a little CI pipeline and make sure the project is ✨ Clippy Clean ✨

**Comment by kanerogers** [comment]
![yes](https://www.reactiongifs.com/wp-content/uploads/2013/01/youre-awesome.gif)

**Comment by LPGhatguy** [comment]
All done!
